In [13]:
import numpy as np

In [14]:
vec = np.array([1, 2, 3])
vec.ndim

1

In [15]:
mat = np.array([[1, 2, 3],[1, 2, 3]],dtype = 'int64')
mat.ndim

2

Чтобы узнать длину массива по каждой из осей, можно воспользоваться атрибутом shape:

In [16]:
vec.shape

(3,)

Чтобы узнать тип элемента и их размер в байтах:

In [17]:
mat.dtype.name

'int64'

In [18]:
mat.itemsize

8

### Создание массивов
* Передать итерируемый объект в качестве параметра функции array (можно также явно указать тип элементов)

In [19]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [20]:
A = np.array([1, 2, 3], dtype = float)
A

array([1., 2., 3.])

In [21]:
B = np.array([(1, 2, 3), (4, 5, 6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

* Создание массивов специального вида при помощи функций zeros, ones, empty, identity:

In [22]:
np.zeros((3,))

array([0., 0., 0.])

In [23]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.empty((2, 5))

array([[1.20962746e-312, 0.00000000e+000, 1.06395697e+224,
        1.53208117e-047, 2.63311994e-052],
       [1.51823979e-051, 1.92014793e-052, 4.50018555e-086,
        3.51151606e+151, 1.33375100e+241]])

Обратите внимание, что содержимое массива, созданного при помощи функции empty, не инициализируется, то есть в качестве значений он может содержать "мусор".
* Создание последовательностей при помощи функций arange (в качестве параметров принимает левую и правую границы последовательности и шаг) и linspace (принимает левую и правую границы и количество элементов)