#NymPy


In [1]:
import numpy as np
vec = np.array([1, 2, 3])
vec.ndim 

1

In [2]:
mat = np.array([[1,2,3], [4,5,6]])
mat.ndim

2

In [3]:
vec.shape

(3,)

In [4]:
mat.dtype.name

'int64'

In [5]:
mat.itemsize

8

#Массивы

In [6]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [7]:
A = np.array([1,2,3], dtype = float)
A

array([1., 2., 3.])

In [8]:
B = np.array([(1,2,3), (4,5,6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.zeros((3,))

array([0., 0., 0.])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.empty((2,5))

array([[1.23307323e-316, 1.77863633e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.01405559e-070, 1.77296434e+160, 5.20477840e-090,
        2.74261700e-057, 8.07320706e-315]])

In [13]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [14]:
np.arange(2.5,8.7,0.9)

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [15]:
np.linspace(2,18,14)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [16]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.arange(8).reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
C=np.arange(6).reshape(2,-1)
C

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
C.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [20]:
A = np.arange(6).reshape(2,-1)
np.hstack((A,A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [21]:
np.vstack((A,A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [22]:
np.concatenate((A,A**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [23]:
a = np.arange(3)
np.tile(a,(2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [24]:
np.tile(a,(4,1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#Базовые операции

In [25]:
A = np.arange(9).reshape(3,3)
B = np.arange(1,10).reshape(3,3)

In [26]:
print (A)
print (B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
A+B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [28]:
A*1.0/B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [29]:
A+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
3*A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [31]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [32]:
A*B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [33]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [34]:
np.tile(np.arange(0,40,10),(3,1)).T+np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [35]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [36]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
A.min()

0

In [38]:
A.max(axis=0)

array([6, 7, 8])

In [39]:
A.sum(axis=1)

array([ 3, 12, 21])

#Индексация

In [40]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[2:5]

array([2, 3, 4])

In [42]:
a[3:8:2]

array([3, 5, 7])

In [43]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [44]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [45]:
A[:,2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [46]:
A[2:4,2:4]

array([[20, 21],
       [29, 30]])

In [47]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [48]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [49]:
A[[2,4,5],[0,1,3]]

array([18, 37, 48])

In [50]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
A[A%5!=3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [52]:
A[np.logical_and(A!=7, A%5!=3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

#Pandas


In [53]:
import pandas as pd
my_series = pd.Series([5,6,7,8,9,10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [54]:
my_series.index

RangeIndex(start=0, stop=6, step=1)

In [55]:
my_series.values

array([ 5,  6,  7,  8,  9, 10])

In [56]:
my_series[4]

9

In [57]:
my_series2 = pd.Series([5,6,7,8,9,10], index=['a','b','c','d','e','f'])
my_series2['f']

10

In [58]:
my_series2[['a','b','f']]

a     5
b     6
f    10
dtype: int64

In [59]:
my_series2[['a','b','f']] = 0
my_series2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [60]:
my_series2[my_series2>0]

c    7
d    8
e    9
dtype: int64

In [61]:
my_series2[my_series2>0]*2

c    14
d    16
e    18
dtype: int64

In [62]:
my_series3 = pd.Series({'a': 5, 'b':6, 'c':7,'d':8})
my_series3

a    5
b    6
c    7
d    8
dtype: int64

In [63]:
my_series3.name = 'numbers'
my_series3.index.name = 'letters'
my_series3

letters
a    5
b    6
c    7
d    8
Name: numbers, dtype: int64

In [64]:
my_series3.index = ['A','B','C','D']
my_series3

A    5
B    6
C    7
D    8
Name: numbers, dtype: int64

#DataFrame

In [65]:

df = pd.DataFrame({
    'country':['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square':[272490, 17125191, 207600, 603628]
})
df

country  population    square
0  Kazakhstan       17.04    272490
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [66]:
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [67]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [68]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [69]:
df = pd.DataFrame({
    'country':['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square':[2724902, 17125191, 207600, 603628]
}, index=['KZ','RU','BY',"UA"])
df

country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UA     Ukraine       45.50    603628

In [70]:
df.index = ['KZ','RU','BY',"UA"]
df.index.name = 'Country Code'
df

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [71]:
df.loc['KZ']

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [72]:
df.iloc[0]

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [73]:
df.loc[['KZ', 'RU'], 'population']

Country Code
KZ     17.04
RU    143.50
Name: population, dtype: float64

In [74]:
df.loc['KZ':'BY', :]

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600

In [75]:
df[df.population > 10][['country', 'square']]

country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
UA               Ukraine    603628

In [76]:
df.reset_index()

Country Code     country  population    square
0           KZ  Kazakhstan       17.04   2724902
1           RU      Russia      143.50  17125191
2           BY     Belarus        9.50    207600
3           UA     Ukraine       45.50    603628

In [77]:
df['density']=df['population']/df['square']*1000000
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

In [78]:
df.drop(['density'], axis = 'columns')

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [79]:
df = df.rename(columns={'Country Code': 'country_code'})
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

#Группировка и агрегирование в pandas

In [80]:
import pandas as pd
from google.colab import files

In [81]:
titanic_df = pd.read_csv('train.csv')
print(titanic_df.head())

FileNotFoundError: ignored

In [ ]:
print(titanic_df.groupby(['Sex', 'Survived'])['PassengerId'].count())

In [ ]:
print(titanic_df.groupby(['Pclass', 'Survived'])['PassengerId'].count())

In [ ]:
%matplotlib inline

In [ ]:
pass_data = pd.read_csv('train.csv')
pass_data

In [ ]:
pass_data.head(3)

In [ ]:
pass_data.columns

In [ ]:
pass_data[2:5]

In [ ]:
pass_data.iloc[1:5, 1:3]

In [ ]:
pass_data['Name'].head()

In [ ]:
pass_data[['Name', 'Sex', 'Parch']].head()

In [ ]:
pass_data[pass_data['Sex'] == 'female'].head()

In [ ]:
pass_data[(pass_data['Sex'] == 'female') & (pass_data['Age'] >= 60) | (pass_data['Sex'] == 'male')].head()

In [ ]:
pass_data[(pass_data.Sex == 'female') &
          (pass_data.Age > 18) &
          (pass_data.Age < 25) &
          (pass_data.SibSp == 0) &
          (pass_data.Parch == 0)].shape

In [ ]:
pass_data.Age.hist(bins = 30)

#Редактирование DataFrame

In [ ]:
pass_data.rename(columns={'Sex': 'sex'}, inplace=True)
pass_data.head()

In [ ]:
def get_last_name(Name):
    return Name.split(',')[0].strip()

last_names = pass_data['Name'].apply(get_last_name)
last_names.head()

In [ ]:
pass_data['Last_name'] = last_names
pass_data.head()

In [ ]:
pass_data.drop('Last_name', axis=1, inplace=True)
pass_data.head()

In [ ]:
pass_data.sort_values(by=['Pclass', 'Fare'], ascending=True).head()

In [ ]:
pass_data.sort_values(by=['Pclass', 'Fare'], ascending=[True, False]).head()

#Группировка данных

In [ ]:
pass_data.groupby('sex')

In [ ]:
pass_data.groupby('sex')['Pclass'].value_counts()

In [ ]:
pass_data.groupby('Pclass')['Fare'].describe()

In [ ]:
pass_data.groupby('sex')['Age'].mean()

In [ ]:
pass_data.groupby('sex')['Survived'].mean()

In [ ]:
pass_data.groupby('Pclass')['Survived'].mean()

In [ ]:
pass_data.groupby('sex', as_index=False)['Survived'].mean()