In [ ]:
import numpy as np
vec = np.array([1,2,3])
vec.ndim


1

In [ ]:

mat = np.array([[1,2,3],[4,5,6]])
mat.ndim

2

In [ ]:
vec.shape

(3,)

In [ ]:
mat.dtype.name

'int64'

In [ ]:
mat.itemsize

8

In [ ]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [ ]:
A = np.array([1,2,3], dtype = float)
A

array([1., 2., 3.])

In [ ]:
B = np.array([(1,2,3),(4,5,6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.zeros((3,))

array([0., 0., 0.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty((2,5))

array([[4.68131083e-310, 6.01347002e-154, 6.01386450e-154,
        5.29421827e+160, 6.01347002e-154],
       [1.14114979e+243, 6.03685735e-154, 6.01346953e-154,
        2.18187188e+243, 1.30388021e-076]])

In [ ]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [ ]:
np.arange(2.5, 8.7, 0.9)

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [ ]:
np.linspace(2,18,14)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.arange(8).reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
C= np.arange(6).reshape(2,-1)
C

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
C.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
A = np.arange(6).reshape(2,-1)
np. hstack((A, A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [ ]:
np.vstack((A, A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [ ]:
np.concatenate((A,A**2), axis=1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [ ]:
a = np.arange(3)
np.tile(a,(2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [ ]:
np.tile(a,(4,1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)

In [ ]:
print (A)
print (B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [ ]:
A * 1.0 / B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [ ]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
3 * A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [ ]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [ ]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [ ]:
np.tile(np.arange(0,40,10),(3,1)).T + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
A.min()

0

In [ ]:
A.max(axis = 0)

array([6, 7, 8])

In [ ]:
A.sum(axis = 1)

array([ 3, 12, 21])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:5]

array([2, 3, 4])

In [ ]:
a[3:8:2]

array([3, 5, 7])

In [ ]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [ ]:
A[2:4,2:4]

array([[20, 21],
       [29, 30]])

In [ ]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [ ]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
A[[2,4,5],[0,1,3]]

array([18, 37, 48])

In [ ]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
A[A % 5 !=3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [ ]:
A[np.logical_and(A !=7, A % 5 !=3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [ ]:
import time
A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [ ]:
start = time.process_time()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.process_time() - start)

0.3142236340000002


In [ ]:
start = time.process_time()
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range (1000000)])
print(time.process_time() - start)

0.2715466470000001


In [ ]:
start = time.process_time()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.process_time() - start)

0.004977000000000231


In [ ]:
start = time.process_time()
ans = A_quick_arr.dot(B_quick_arr)
print(time.process_time() - start)

0.003970554000000348


In [ ]:
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [ ]:
my_series.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
my_series.values

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
my_series[4]

9

In [ ]:
my_series2 = pd.Series([5, 6, 7, 8, 9, 10], index = ['a', 'b', 'c', 'd', 'e', 'f'])
my_series2['f']

10

In [ ]:
my_series2[['a', 'b', 'f']]

a     5
b     6
f    10
dtype: int64

In [ ]:
my_series2[['a', 'b', 'f']] = 0
my_series2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [ ]:
my_series2[my_series2 > 0]

c    7
d    8
e    9
dtype: int64

In [ ]:
my_series2[my_series2 > 0] * 2

c    14
d    16
e    18
dtype: int64

In [ ]:
my_series3 = pd.Series({'a' : 5, 'b' : 6, 'c' : 7, 'd' : 8})
my_series3

a    5
b    6
c    7
d    8
dtype: int64

In [ ]:
my_series3.name = 'numbers'
my_series3.index.name = 'letters'
my_series3

letters
a    5
b    6
c    7
d    8
Name: numbers, dtype: int64

In [ ]:
my_series3.index = ['A', 'B', 'C', 'D']
my_series3

A    5
B    6
C    7
D    8
Name: numbers, dtype: int64

In [ ]:
df = pd.DataFrame({
    'country' : ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population' : [17.04, 143.5, 9.5, 45.5],
    'square' : [2724902, 17125191, 207600, 603628]
})
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [ ]:
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [ ]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df = pd.DataFrame({
        'country' : ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
        'population' : [17.04, 143.5, 9.5, 45.5],
        'square' : [2724902, 17125191, 207600, 603628]
    }, index = ['KZ', 'RU', 'BY', 'UA'])
df

country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UA     Ukraine       45.50    603628

In [ ]:
df.index = ['KZ', 'RU', 'BY', 'UA']
df.index.name = 'Country Code'
df

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [ ]:
df['country']

Country Code
KZ    Kazakhstan
RU        Russia
BY       Belarus
UA       Ukraine
Name: country, dtype: object

In [ ]:
df.loc['KZ']

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [ ]:
df.iloc[0]

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [ ]:
df.loc[['KZ','RU'], 'population']

Country Code
KZ     17.04
RU    143.50
Name: population, dtype: float64

In [ ]:
df.loc['KZ' : 'BY', :]

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600

In [ ]:
df[df.population > 10][['country', 'square']]

country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
UA               Ukraine    603628

In [ ]:
df.reset_index()

Country Code     country  population    square
0           KZ  Kazakhstan       17.04   2724902
1           RU      Russia      143.50  17125191
2           BY     Belarus        9.50    207600
3           UA     Ukraine       45.50    603628

In [ ]:
df['denisty'] = df['population'] / df['square'] * 1000000
df

country  population    square    denisty
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

In [ ]:
df.drop(['denisty'], axis = 'columns')

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [ ]:
df = df.rename(columns = {'Country Code': 'country_code'})
df

country  population    square    denisty
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

In [ ]:
drive.mount('/content/MyDrive/MyDrive/')

ValueError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/MyDrive/MyDrive/', force_remount=True)

ValueError: ignored

In [ ]:
import pandas as pd
df = pd.read_csv('titanic3.csv', sep=';')
df.head()

FileNotFoundError: ignored