<a href="https://colab.research.google.com/github/artem-bezrukov/spring_2022/blob/main/ml/lab_1/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
vec=np.array([1,2,3])
vec.ndim


1

In [ ]:
mat = np.array([[1,2,3],[4,5,6]])
mat.ndim

2

In [ ]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
vec.shape

(3,)

In [ ]:
mat.dtype.name

'int64'

In [ ]:
mat.dtype.itemsize

8

In [ ]:
A=np.array([1,2,3])
A


array([1, 2, 3])

In [ ]:
A=np.array([1,2,3], dtype=float)
A


array([1., 2., 3.])

In [ ]:
B=np.array([(1,2,3),(4,5,6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.zeros((3,))

array([0., 0., 0.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty((2,5))

array([[4.67942406e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [ ]:
np.arange(2,20,3)


array([ 2,  5,  8, 11, 14, 17])

In [ ]:
np.arange(2.5, 8.7, 0.9)

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [ ]:
np.linspace(2,18,14)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.arange(8).reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
C=np.arange(8).reshape(2,-1)
C

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
C.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
A=np.arange(6).reshape(2,-1)
np.hstack((A,A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [ ]:
np.vstack((A,A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [ ]:
np.concatenate((A,A**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [ ]:
a=np.arange(3)
np.tile(a,(2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [ ]:
A=np.arange(9).reshape(3,3)
B=np.arange(1,10).reshape(3,3)

In [ ]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
A+B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [ ]:
A*1.0/B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [ ]:
A+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
3*A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [ ]:
A **2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
A*B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [ ]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [ ]:
np.tile(np.arange(0,40,10),(3,1)).T +np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [ ]:
A


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
A.min()

0

In [ ]:
A.max(axis=0)

array([6, 7, 8])

In [ ]:
A.sum(axis=0)

array([ 9, 12, 15])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:5]

array([2, 3, 4])

In [ ]:
a[3:8:2]

array([3, 5, 7])

In [ ]:
A=np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
A[:,2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [ ]:
A[2:4,2:4]

array([[20, 21],
       [29, 30]])

In [ ]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [ ]:
A=np.arange(81).reshape(9,-1)
A


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
A[[2,4,5],[0,1,3]]

array([18, 37, 48])

In [ ]:
A=np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
A[A%5 !=3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [ ]:
A[np.logical_and(A!=7,A%5!=3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])