# 1 - Numpy

In [7]:
import numpy as np

In [8]:
vec = np.array([1, 2, 3])
vec.ndim # количество осей

1

In [10]:
mat = np.array([[1,2,3], [4,5,6]])
mat.ndim

2

In [11]:
# Чтобы узнать длину массива по каждой из осей, можно воспользоваться атрибутом shape:
vec.shape

(3,)

In [12]:
# Чтобы узнать тип элементов и их размер в байтах:
mat.dtype.name

'int32'

In [13]:
mat.itemsize

4

In [ ]:
# Cоздание массивов

In [14]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [16]:
A = np.array([1, 2, 3], dtype = float)
A

array([1., 2., 3.])

In [17]:
B = np.array([(1, 2, 3), (4, 5, 6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Создание массивов специального вида при помощи функций zeros, ones, empty, identity

In [18]:
np.zeros((3,))

array([0., 0., 0.])

In [19]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.empty((2, 5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.00133926e-307, 2.67015654e-306],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307, 1.42419530e-306]])

In [22]:
# Создание последовательностей при помощи функции функций:
# 1) arenge (в качестве параметров левая и правая границы, шаг)
# 2) linspace (в качестве параметров левая и правая границы, кол-во эл-тов)

In [23]:
np.arange(2, 20, 3) # аналогично стандартной функции range python, правая граница не вллючается

array([ 2,  5,  8, 11, 14, 17])

In [24]:
np.arange(2.5, 8.7, 0.9) # но может работать и с вещественными веществами

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [25]:
np.linspace(2, 18, 14) # правая граница включается (по умолчанию)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [ ]:
# Для изменения размеров существующего массива можно воспользоваться функцией reshape
# Кол-во элементов должно оставаться неизменным

In [26]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Вместо значения длины можно указать -1, в таком случае она будет рассчитана автоматически

In [27]:
np.arange(8).reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# Транспорирование массива

In [28]:
C = np.arange(6).reshape(2, -1)
C

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
C.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
# Объединение существующих массивов по заданной оси:

In [30]:
A = np.arange(6). reshape(2, - 1)
np.hstack((A, A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [31]:
np.vstack((A, A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [32]:
np.concatenate((A, A**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [ ]:
# Повторение существующего массива

In [41]:
a = np.arange(3)
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [42]:
np.tile(a, (4, 1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
# Базовые операции

In [ ]:
# Базовые арифметические операции над массивами выполняются поэлементно:

In [44]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)

In [46]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [48]:
A * 1.0 / B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [49]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
3 * A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [51]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [52]:
# Умножение массивов является поэлементным, а не матричным
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [53]:
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [54]:
# Универсальные функции (sin, cos, exp и тд.) тажке выполняются поэлементно
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [55]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
A.min()

0

In [59]:
A.max(axis = 0)

array([6, 7, 8])

In [60]:
A.sum(axis = 1)

array([ 3, 12, 21])

In [61]:
# Индексация

In [63]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a[2:5]

array([2, 3, 4])

In [65]:
a[3:8:2]

array([3, 5, 7])

In [66]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [67]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [68]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [69]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [70]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [ ]:
# Также может использоваться индексация при помощи списков индексов
# (по каждой из осей)

In [71]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [72]:
A[[2, 4, 5], [0, 1, 3]]

array([18, 37, 48])

In [ ]:
# Может также использоваться логическая индексация 

In [73]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [75]:
# Также можно использовать логические операции:
A[np.logical_and(A != 7, A % 5 != 3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [76]:
## Зачем?
# Зачем использовать NumPy, если сузествуют стандартные списки/кортежи 
# Причина заключается в скорости работы. Посмотрим на примере:

In [77]:
# С использованием обычных списков и циклов:

In [78]:
import time
A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [83]:
start = time.perf_counter()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.perf_counter() - start) # время выполнения в секундах

0.2764387000006536


In [84]:
start = time.perf_counter()
ans = sum([A_slow_list[i]*B_slow_list[i] for o in range(1000000)])
print(time.perf_counter() - start)

0.24514470000030997


In [ ]:
# А теперь используем NumPy

In [86]:
start = time.perf_counter()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.perf_counter() - start)


0.0037260000008245697


In [87]:
start = time.perf_counter()
ans = A_quick_arr.dot(B_quick_arr)
print(time.perf_counter() - start)

0.0009481999986746814


In [ ]:
# Как мы видим, с использованием NumPy вычисление сумммы поэлементных произведений двух больших векторов вычисляется гораздо быстрее

# Pandas

In [ ]:
# Series

In [89]:
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [90]:
my_series.index

RangeIndex(start=0, stop=6, step=1)

In [91]:
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [92]:
my_series[4]

9

In [93]:
# Индексы можно задавать явно:
my_series2 = pd.Series([5, 6, 7, 8, 9, 10], index=['a', 'b', 'c', 'd', 'e', 'f'])
my_series2['f']

10

In [ ]:
# Делать выборку по нескольким элементам и осуществлять групповое присваивание:

In [94]:
my_series2[['a', 'b', 'f']]

a     5
b     6
f    10
dtype: int64

In [95]:
my_series2[['a', 'b', 'f']] = 0
my_series2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [96]:
# Можно комбинировать фильтрацию series и мат. операции:

In [97]:
my_series2[my_series2 > 0]

c    7
d    8
e    9
dtype: int64

In [98]:
my_series2[my_series2 > 0] * 2

c    14
d    16
e    18
dtype: int64

In [100]:
# Можно задавать Series таким образом:
my_series3 = pd.Series({'a': 5, 'b' : 6, 'c': 7, 'd': 8})
my_series3

a    5
b    6
c    7
d    8
dtype: int64

In [ ]:
# У объекта Series и его индекса есть атрибут name, задающий имя объекту и индексу соответственно

In [102]:
my_series3.name = 'numbers'
my_series3.index.name = 'letters'
my_series3

letters
a    5
b    6
c    7
d    8
Name: numbers, dtype: int64

In [ ]:
# Индексы можно поменять на лету:

In [103]:
my_series3.index = ['A', 'B', 'C', 'D']
my_series3

A    5
B    6
C    7
D    8
Name: numbers, dtype: int64

# DataFrame

In [ ]:
# Объект DataFrame - это табличная структура данных, столбцами которой выступают объекты Series

In [104]:
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
})
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [105]:
# Убедимся, что столбец в DataFrame это Series:

In [106]:
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [107]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [108]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [109]:
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
}, index=['KZ', 'RU', 'BY', 'UA'])
df

country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UA     Ukraine       45.50    603628

In [110]:
df.index = ['KZ', 'RU', 'BY', 'UA']
df.index.name = 'Country Code'
df

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [111]:
df['country']

Country Code
KZ    Kazakhstan
RU        Russia
BY       Belarus
UA       Ukraine
Name: country, dtype: object

In [112]:
df.loc['KZ']

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [114]:
df.iloc[0]

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [115]:
df.loc[['KZ', 'RU'], 'population']

Country Code
KZ     17.04
RU    143.50
Name: population, dtype: float64

In [116]:
df.loc['KZ':'BY', :]

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600

In [117]:
df[df.population > 10][['country', 'square']]

country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
UA               Ukraine    603628

In [118]:
df.reset_index()

Country Code     country  population    square
0           KZ  Kazakhstan       17.04   2724902
1           RU      Russia      143.50  17125191
2           BY     Belarus        9.50    207600
3           UA     Ukraine       45.50    603628

In [121]:
df['density'] = df['population'] / df['square'] * 1000000
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

In [123]:
df.drop(['density'], axis = 'columns')

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [131]:
df = df.rename(columns={'Country Code':'country_code'})
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

# Группировка и агрегирование в pandas

In [140]:
titanic_df = pd.read_csv('D:\Всякое\политех\Машинное обучение\ЛР 1\titanic3.csv')
print(titanic_df.head())

OSError: [Errno 22] Invalid argument: 'D:\\Всякое\\политех\\Машинное обучение\\ЛР 1\titanic3.csv'